mopidy:
    env_file: logins.env
    image: "ivdata/mopidy"
    ports:
        - "6680:6680"
        - "6600:6600"
    volumes:
        - fifo:/tmp/
        - ./music:/media

snapserver:
    image: "ivdata/snapserver"
    ports:
        - "1704:1704"
        - "1705:1705"
    volumes:
        - fifo:/tmp/
    environment:
        - stream_name=Mopidy
